<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-700">{{ __('governance.approvals_eyebrow') }}</p><h1 class="mt-1 text-2xl font-black text-slate-950">{{ __('governance.approvals_title') }}</h1><p class="mt-1 text-sm text-slate-500">{{ __('governance.approvals_subtitle') }}</p></div><span class="rounded-full bg-amber-100 px-3 py-1.5 text-sm font-bold text-amber-800">{{ __('governance.pending_count', ['count' => $pendingCount]) }}</span></div></x-slot>
    <div class="space-y-5 py-6">
        <div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4 shadow-sm"><div class="flex gap-2">@foreach(__('governance.filters') as $value=>$label)<a href="{{ route('owner.approvals.index', ['status'=>$value ?: null]) }}" @class(['rounded-lg px-3 py-2 text-sm font-semibold','bg-blue-700 text-white'=>request('status','')===$value,'bg-slate-100 text-slate-600'=>request('status','')!==$value])>{{ $label }}</a>@endforeach</div><p class="text-xs text-slate-500">{{ __('governance.maker_checker') }}</p></div>
        <div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">{{ __('governance.request') }}</th><th class="px-5 py-3">{{ __('governance.requested_by') }}</th><th class="px-5 py-3">{{ __('governance.amount') }}</th><th class="px-5 py-3">{{ __('governance.status') }}</th><th class="px-5 py-3">{{ __('governance.decision') }}</th></tr></thead><tbody class="divide-y">
        @forelse($approvals as $approval)<tr class="align-top hover:bg-slate-50"><td class="px-5 py-4"><p class="font-bold">{{ str($approval->action_type)->replace('.',' ')->headline() }}</p><p class="text-xs text-slate-500">{{ $approval->subject?->expense_number ?? class_basename($approval->subject_type).' #'.$approval->subject_id }}</p><p class="mt-1 max-w-xs text-xs text-slate-400">{{ $approval->request_reason }}</p></td><td class="px-5 py-4"><p class="font-medium">{{ $approval->requester->name }}</p><p class="text-xs text-slate-500">{{ $approval->created_at->diffForHumans() }}</p></td><td class="px-5 py-4 font-bold">{{ $approval->amount ? $business->currency.' '.number_format($approval->amount,2) : '—' }}</td><td class="px-5 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold','bg-amber-100 text-amber-800'=>$approval->status->value==='pending','bg-emerald-100 text-emerald-800'=>$approval->status->value==='approved','bg-rose-100 text-rose-800'=>in_array($approval->status->value,['rejected','returned'])])>{{ ucfirst($approval->status->value) }}</span></td><td class="px-5 py-4">
        @if($approval->status->value==='pending')<form method="POST" action="{{ $approval->subject instanceof \App\Models\Expense ? route('owner.expenses.approvals.decision',$approval) : route('owner.approvals.decision',$approval) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<input name="reason" required placeholder="{{ __('governance.decision_note') }}" class="w-36 rounded-lg border-slate-300 text-xs"><button name="decision" value="approve" class="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">{{ __('governance.approve') }}</button><button name="decision" value="reject" class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">{{ __('governance.reject') }}</button></form>@else<p class="text-xs text-slate-500">{{ $approval->decider?->name ?? __('governance.waiting_reviewer') }}@if($approval->decision_reason)<br>{{ $approval->decision_reason }}@endif</p>@endif
        </td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">{{ __('governance.no_approvals') }}</td></tr>@endforelse
        </tbody></table></div><div class="border-t p-4">{{ $approvals->links() }}</div></div>
    </div>
</x-app-layout>
