<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-700">Operations</p><h1 class="mt-1 text-2xl font-bold">{{ $mode === 'projects' ? 'Projects / Udhabauni' : 'Layaway / Kubandika' }}</h1></div></x-slot>
    @php($money = fn ($amount) => $business->currency.' '.number_format((float) $amount, 2))
    <div class="mx-auto max-w-[1600px] px-4 py-5" x-data="{ create:false }">
        @if(session('status'))<div class="mb-4 rounded-lg bg-emerald-50 p-3 text-emerald-800">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-4 rounded-lg bg-rose-50 p-3 text-rose-800">{{ $errors->first() }}</div>@endif
        <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-slate-500">{{ $mode === 'projects' ? 'Track contracts, materials taken from stock, and payments.' : 'Record products and instalments. Stock stays available until collection.' }}</p></div><button @click="create=true" class="rounded-lg bg-blue-700 px-4 py-2.5 font-bold text-white">+ Create new {{ $mode === 'projects' ? 'project' : 'layaway' }}</button></div>
        <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
            @if($mode === 'projects')
                <x-summary-card label="Projects" :value="$summary['count']" /> <x-summary-card label="Contract value" :value="$money($summary['contract'])" /> <x-summary-card label="Paid amount" :value="$money($summary['paid'])" /> <x-summary-card label="Stock value taken" :value="$money($summary['issued'])" /> <x-summary-card label="Payment remaining" :value="$money($summary['remaining'])" />
            @else
                <x-summary-card label="Layaway plans" :value="$summary['count']" /> <x-summary-card label="Products target value" :value="$money($summary['target'])" /> <x-summary-card label="Amount paid" :value="$money($summary['paid'])" /> <x-summary-card label="Amount remaining" :value="$money($summary['remaining'])" />
            @endif
        </section>
        <section class="mt-7"><div class="mb-3 flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-lg font-bold">History</h2><p class="text-sm text-slate-500">Open a card to see the full record and activity.</p></div><form class="flex flex-wrap gap-2" method="GET"><input name="search" value="{{ request('search') }}" class="rounded-lg border" placeholder="Search name, customer or number"><select name="customer_id" class="rounded-lg border" onchange="this.form.submit()"><option value="">All customers</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)request('customer_id')===$customer->id)>{{ $customer->name }}</option>@endforeach</select><select name="status" class="rounded-lg border" onchange="this.form.submit()"><option value="">All statuses</option>@foreach($mode==='projects' ? ['active','paid','completed','completed_pending_payment'] : ['active','ready_for_collection','collected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',ucfirst($status)) }}</option>@endforeach</select><select name="per_page" class="rounded-lg border" onchange="this.form.submit()">@foreach([6,9,12,24] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }} per page</option>@endforeach</select><button class="rounded-lg border px-3 py-2">Filter</button></form></div>
            <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                @foreach($mode === 'projects' ? $projects : $plans as $record)
                    @php($issued = $mode==='projects' ? $record->materialIssues->sum(fn($issue) => $issue->items->sum(fn($item) => (float)$item->quantity*(float)$item->conversion_factor*(float)$item->unit_cost)) : 0)
                    <a href="{{ $mode==='projects' ? route('owner.projects.show',$record) : route('owner.layaway.show',$record) }}" class="rounded-xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-400"><div class="flex items-start justify-between gap-2"><div><p class="font-bold">{{ $mode==='projects' ? $record->name : $record->plan_number }}</p><p class="mt-1 text-sm text-slate-500">{{ $record->customer->name }}</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold uppercase">{{ str_replace('_',' ',$record->status) }}</span></div><div class="mt-5 grid grid-cols-2 gap-3 border-t pt-4 text-sm"><div><p class="text-slate-500">{{ $mode==='projects' ? 'Contract' : 'Target' }}</p><p class="font-bold">{{ $money($mode==='projects' ? $record->contract_amount : $record->target_amount) }}</p></div><div><p class="text-slate-500">Paid</p><p class="font-bold text-emerald-700">{{ $money($record->paid_amount) }}</p></div>@if($mode==='projects')<div><p class="text-slate-500">Stock taken</p><p class="font-bold text-amber-700">{{ $money($issued) }}</p></div><div><p class="text-slate-500">Payment remaining</p><p class="font-bold">{{ $money((float)$record->contract_amount-(float)$record->paid_amount) }}</p></div>@else<div><p class="text-slate-500">Items</p><p class="font-bold">{{ $record->items->count() }}</p></div><div><p class="text-slate-500">Remaining</p><p class="font-bold">{{ $money((float)$record->target_amount-(float)$record->paid_amount) }}</p></div>@endif</div><p class="mt-4 text-sm font-bold text-blue-700">Open details →</p></a>
                @endforeach
            </div>
            <div class="mt-5">{{ ($mode==='projects' ? $projects : $plans)->links() }}</div>
        </section>
        <div x-show="create" x-cloak class="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div @click.outside="create=false" class="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6"><div class="flex justify-between"><h2 class="text-xl font-bold">Create {{ $mode==='projects' ? 'project' : 'layaway plan' }}</h2><button @click="create=false">✕</button></div><form method="POST" action="{{ $mode==='projects' ? route('owner.commitments.projects.store') : route('owner.commitments.layaways.store') }}" class="mt-5 grid gap-3">@csrf<select name="customer_id" required class="rounded-lg border"><option value="">Customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select>@if($mode==='projects')<input name="name" required class="rounded-lg border" placeholder="Project name"><input name="location" class="rounded-lg border" placeholder="Site location"><input name="contract_amount" type="number" min="1" step="0.01" required class="rounded-lg border" placeholder="Contract amount"><select name="payment_mode" class="rounded-lg border"><option value="completion">Full payment at completion</option><option value="milestone">Milestone payments</option></select><input name="start_date" type="date" class="rounded-lg border"><input name="completion_date" type="date" class="rounded-lg border">@else<input name="target_amount" type="number" min="1" step="0.01" required class="rounded-lg border" placeholder="Target amount"><input name="collection_due_date" type="date" class="rounded-lg border">@endif<textarea name="notes" class="rounded-lg border" placeholder="Notes"></textarea><button class="rounded-lg bg-blue-700 py-3 font-bold text-white">Create</button></form></div></div>
    </div>
</x-app-layout>
