<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <div><p class="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{{ $business->name }}</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ __('catalogue.title') }}</h1><p class="mt-1 text-sm text-slate-500">{{ __('catalogue.subtitle') }}</p></div>
            <span class="rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700">{{ __('catalogue.products_count', ['count' => $products->total()]) }}</span>
        </div>
    </x-slot>

    <div class="mx-auto max-w-[1600px] space-y-4 px-4 py-6 sm:px-6 lg:px-8" x-data="{ panel: @js(in_array(request('panel'), ['products','setup','pricing'], true) ? request('panel') : 'products'), addOpen: @js(request('create') === 'product'), importOpen: false, analyticsOpen: false, filtersOpen: {{ request()->hasAny(['category','brand','stock_status','status','price_level']) ? 'true' : 'false' }} }" @keydown.escape.window="addOpen = importOpen = analyticsOpen = false">
        @if (session('status')) <div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-semibold text-emerald-700">{{ session('status') }}</div> @endif
        @if ($errors->any()) <div class="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700"><p class="font-bold">{{ __('catalogue.fix_errors') }}</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif

        <div class="flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">
            @foreach (__('catalogue.tabs') as $key=>$label)<button type="button" @click="panel='{{ $key }}'" :class="panel==='{{ $key }}' ? 'bg-blue-700 text-white shadow' : 'text-slate-600 hover:bg-slate-50'" class="whitespace-nowrap rounded-xl px-5 py-3 text-sm font-bold transition">{{ $label }}</button>@endforeach
        </div>

        <section x-show="panel==='products'" class="space-y-6">
            <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="text-2xl font-black">{{ __('catalogue.management_title') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('catalogue.management_subtitle', ['count' => number_format($productMetrics['totalProducts'])]) }}</p></div><div class="flex flex-wrap gap-2"><button type="button" @click="analyticsOpen=true" class="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100">▥ {{ __('catalogue.analytics') }}</button>@can('create', \App\Models\Product::class)<button type="button" @click="importOpen=true" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">⇧ {{ __('catalogue.import') }}</button>@endcan<a href="{{ route('owner.catalogue.export') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">⇩ {{ __('catalogue.export') }}</a>@can('create', \App\Models\Product::class)<button type="button" @click="addOpen=true" class="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">＋ {{ __('catalogue.add_product_button') }}</button>@endcan</div></div>

            <div class="grid grid-cols-2 gap-3 xl:grid-cols-4">@foreach([[__('catalogue.total_products'),number_format($productMetrics['totalProducts']),'text-blue-700','bg-blue-50'],[__('catalogue.active_products'),number_format($productMetrics['activeProducts']),'text-emerald-700','bg-emerald-50'],[__('catalogue.low_out_stock'),number_format($productMetrics['lowStockProducts']),'text-amber-700','bg-amber-50'],[__('catalogue.total_stock_value'),$business->currency.' '.number_format($productMetrics['stockValue'],2),'text-sky-700','bg-sky-50']] as [$label,$value,$colour,$background])<div class="flex items-center gap-3 rounded-2xl border bg-white p-4 shadow-sm"><span class="flex h-10 w-10 items-center justify-center rounded-xl {{ $background }} {{ $colour }}">◇</span><div><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-1 text-lg font-black {{ $colour }}">{{ $value }}</p></div></div>@endforeach</div>

            <form method="GET" class="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><input type="hidden" name="per_page" value="{{ request('per_page',15) }}"><div class="flex gap-2"><input name="search" value="{{ request('search') }}" class="min-w-0 flex-1 rounded-xl border-slate-200" placeholder="{{ __('catalogue.search_reference') }}"><button type="button" @click="filtersOpen=!filtersOpen" class="rounded-xl border px-4 text-sm font-bold text-slate-600">☷ {{ __('catalogue.filters') }}</button><button class="rounded-xl bg-blue-700 px-4 text-sm font-bold text-white">{{ __('catalogue.apply') }}</button></div><div x-show="filtersOpen" x-cloak class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><select name="category" class="rounded-xl border-slate-200 text-sm"><option value="">{{ __('catalogue.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category')==$category->id)>{{ $category->name }}</option>@endforeach</select><select name="brand" class="rounded-xl border-slate-200 text-sm"><option value="">{{ __('catalogue.all_brands') }}</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(request('brand')==$brand->id)>{{ $brand->name }}</option>@endforeach</select><select name="stock_status" class="rounded-xl border-slate-200 text-sm"><option value="">{{ __('catalogue.all_stock') }}</option><option value="in" @selected(request('stock_status')==='in')>{{ __('catalogue.stock_in') }}</option><option value="low" @selected(request('stock_status')==='low')>{{ __('catalogue.stock_low') }}</option><option value="out" @selected(request('stock_status')==='out')>{{ __('catalogue.stock_out') }}</option></select><select name="status" class="rounded-xl border-slate-200 text-sm"><option value="">{{ __('catalogue.all_statuses') }}</option><option value="active" @selected(request('status')==='active')>{{ __('catalogue.active') }}</option><option value="inactive" @selected(request('status')==='inactive')>{{ __('catalogue.inactive') }}</option></select><select name="price_level" class="rounded-xl border-slate-200 text-sm"><option value="">{{ __('catalogue.all_price_levels') }}</option>@foreach($priceLevels as $level)<option value="{{ $level->id }}" @selected(request('price_level')==$level->id)>{{ $level->name }}</option>@endforeach</select><a href="{{ route('owner.catalogue.index') }}" class="rounded-xl border px-4 py-2.5 text-center text-sm font-bold text-rose-600">{{ __('catalogue.clear') }}</a></div><p class="text-xs text-slate-500">{{ __('catalogue.showing_products', ['shown' => $products->count(), 'total' => $products->total()]) }}</p></form>

            @include('owner.catalogue.partials.product-table')
            @can('create', \App\Models\Product::class)
            <div x-show="addOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/40 p-4" @click.self="addOpen=false"><div class="w-full max-w-5xl rounded-3xl border border-slate-200 bg-white p-6 shadow-2xl">
                <div class="flex justify-between"><h2 class="text-lg font-bold">{{ __('catalogue.add_product') }}</h2><button type="button" @click="addOpen=false" class="text-xl text-slate-400">×</button></div>
                @if ($units->isEmpty())<p class="mt-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">{{ __('catalogue.unit_required') }}</p>@else
                <form method="POST" action="{{ route('owner.catalogue.products.store') }}" class="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">@csrf
                    <label class="text-sm font-semibold">{{ __('catalogue.product_name') }}<input name="name" value="{{ old('name') }}" required class="mt-2 block w-full rounded-xl border-slate-200" placeholder="Portland cement"></label>
                    <label class="text-sm font-semibold">{{ __('catalogue.sku') }} <span class="font-normal text-slate-400">{{ __('catalogue.auto_blank') }}</span><input name="sku" value="{{ old('sku') }}" class="mt-2 block w-full rounded-xl border-slate-200" placeholder="CEM-001"></label>
                    <label class="text-sm font-semibold">{{ __('catalogue.barcode') }}<input name="barcode" value="{{ old('barcode') }}" class="mt-2 block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.optional') }}"></label>
                    <label class="text-sm font-semibold">{{ __('catalogue.base_unit') }}<select name="unit_id" required class="mt-2 block w-full rounded-xl border-slate-200"><option value="">{{ __('catalogue.select_unit') }}</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }} ({{ $unit->symbol }})</option>@endforeach</select></label>
                    <label class="text-sm font-semibold">{{ __('catalogue.category') }}<select name="category_id" class="mt-2 block w-full rounded-xl border-slate-200"><option value="">{{ __('catalogue.none') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label>
                    <label class="text-sm font-semibold">{{ __('catalogue.brand') }}<select name="brand_id" class="mt-2 block w-full rounded-xl border-slate-200"><option value="">{{ __('catalogue.none') }}</option>@foreach($brands as $brand)<option value="{{ $brand->id }}">{{ $brand->name }}</option>@endforeach</select></label>
                    <div class="flex items-end gap-5 pb-3 text-sm"><label class="flex items-center gap-2"><input type="checkbox" name="is_stock_tracked" value="1" checked class="rounded border-slate-300 text-blue-700"> {{ __('catalogue.stock_tracked') }}</label><label class="flex items-center gap-2"><input type="checkbox" name="tracks_expiry" value="1" class="rounded border-slate-300 text-blue-700"> {{ __('catalogue.expiry') }}</label></div>
                    <div class="flex items-end"><button class="w-full rounded-xl bg-blue-700 px-5 py-3 font-bold text-white hover:bg-blue-800">{{ __('catalogue.create_product') }}</button></div>
                </form>@endif
            </div></div>@endcan

            <div class="hidden overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
                <div class="border-b border-slate-100 p-5"><form><input name="search" value="{{ request('search') }}" class="w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.search') }}"></form></div>
                <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">{{ __('catalogue.tabs.products') }}</th><th class="px-5 py-4">{{ __('catalogue.category_brand') }}</th><th class="px-5 py-4">{{ __('catalogue.units') }}</th><th class="px-5 py-4">{{ __('catalogue.current_prices') }}</th><th class="px-5 py-4">{{ __('catalogue.status') }}</th></tr></thead><tbody class="divide-y divide-slate-100">
                    @forelse($products as $product)<tr class="align-top hover:bg-slate-50/70"><td class="px-5 py-4"><p class="font-bold text-slate-900">{{ $product->name }}</p><p class="mt-1 font-mono text-xs text-slate-500">{{ $product->sku }} @if($product->barcode) · {{ $product->barcode }} @endif</p></td><td class="px-5 py-4 text-slate-600">{{ $product->category?->name ?? __('catalogue.uncategorized') }}<br><span class="text-xs text-slate-400">{{ $product->brand?->name ?? __('catalogue.no_brand') }}</span></td><td class="px-5 py-4">@foreach($product->productUnits as $pu)<span class="mb-1 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs">{{ $pu->unit->symbol }}@if($pu->is_base) · {{ __('catalogue.base') }} @else · ×{{ rtrim(rtrim($pu->conversion_factor,'0'),'.') }}@endif</span> @endforeach</td><td class="px-5 py-4">@forelse($product->productUnits->flatMap->prices->where('is_active',true) as $price)<p class="text-xs"><span class="font-semibold">{{ $price->priceLevel->name }}:</span> {{ number_format((float)$price->amount,2) }} {{ $price->currency }}</p>@empty<span class="text-xs text-slate-400">{{ __('catalogue.not_priced') }}</span>@endforelse</td><td class="px-5 py-4"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{{ __('catalogue.active') }}</span></td></tr>
                    @empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">{{ __('catalogue.no_products') }}</td></tr>@endforelse
                </tbody></table></div><div class="border-t border-slate-100 p-5">{{ $products->links() }}</div>
            </div>
        </section>

        <div x-show="importOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" @click.self="importOpen=false"><div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><div><h2 class="text-lg font-black">{{ __('catalogue.import_products') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('catalogue.import_help') }}</p></div><button @click="importOpen=false" class="text-xl">×</button></div><a href="{{ route('owner.catalogue.import-template') }}" class="mt-4 inline-block text-sm font-bold text-blue-700">⇩ {{ __('catalogue.download_template') }}</a><form method="POST" action="{{ route('owner.catalogue.import') }}" enctype="multipart/form-data" class="mt-4 space-y-4">@csrf<input type="file" name="file" accept=".csv,text/csv" required class="block w-full rounded-xl border p-3 text-sm"><button class="w-full rounded-xl bg-blue-700 px-4 py-3 font-bold text-white">{{ __('catalogue.import_now') }}</button></form></div></div>
        @include('owner.catalogue.partials.import-review')
        <div x-show="analyticsOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" @click.self="analyticsOpen=false"><div class="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><h2 class="text-lg font-black">{{ __('catalogue.product_analytics') }}</h2><button @click="analyticsOpen=false" class="text-xl">×</button></div><div class="mt-5 grid grid-cols-2 gap-3">@foreach($categories->sortByDesc(fn($category) => $category->products_count ?? 0)->take(6) as $category)<div class="rounded-xl border p-4"><p class="text-sm font-bold">{{ $category->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $category->products()->where('business_id',$business->id)->count() }} {{ __('catalogue.tabs.products') }}</p></div>@endforeach</div></div></div>

        <section x-show="panel==='setup'" x-cloak class="grid gap-6 lg:grid-cols-3">
            @foreach([[__('catalogue.categories'),'category',route('owner.catalogue.categories.store')],[__('catalogue.brands'),'brand',route('owner.catalogue.brands.store')],[__('catalogue.unit_list'),'unit',route('owner.catalogue.units.store')]] as [$title,$kind,$action])
            <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">{{ $title }}</h2><form method="POST" action="{{ $action }}" class="mt-5 space-y-3">@csrf<input name="name" required class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.name', ['item' => Str::lower($title)]) }}">@if($kind==='unit')<input name="symbol" required class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.symbol') }}"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="allows_decimal" value="1" class="rounded border-slate-300 text-blue-700"> {{ __('catalogue.decimal') }}</label>@endif @if($kind==='category')<select name="parent_id" class="block w-full rounded-xl border-slate-200"><option value="">{{ __('catalogue.no_parent') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@endif<button class="w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">{{ __('catalogue.add', ['item' => Str::lower($title)]) }}</button></form><div class="mt-5 flex flex-wrap gap-2">@foreach(${$kind === 'category' ? 'categories' : ($kind === 'brand' ? 'brands' : 'units')} as $item)<span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold">{{ $item->name }}@if($kind==='unit') · {{ $item->symbol }}@endif</span>@endforeach</div></div>
            @endforeach
            @if($categories->isNotEmpty())<div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><h2 class="text-lg font-bold">{{ __('catalogue.edit_hierarchy') }}</h2><div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($categories as $editableCategory)<form method="POST" action="{{ route('owner.catalogue.categories.update', $editableCategory) }}" class="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-3">@csrf @method('PUT')<input name="name" value="{{ $editableCategory->name }}" required class="rounded-xl border-slate-200"><select name="parent_id" class="rounded-xl border-slate-200"><option value="">{{ __('catalogue.no_parent') }}</option>@foreach($categories->where('id','!=',$editableCategory->id) as $possibleParent)<option value="{{ $possibleParent->id }}" @selected($editableCategory->parent_id === $possibleParent->id)>{{ $possibleParent->name }}</option>@endforeach</select><button class="rounded-xl border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-blue-700">{{ __('catalogue.save_hierarchy') }}</button></form>@endforeach</div></div>@endif
        </section>

        <section x-show="panel==='pricing'" x-cloak class="space-y-6">
            <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">{{ __('catalogue.price_levels') }}</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($priceLevels as $level)<span class="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">{{ $level->name }} · {{ $level->code }}</span>@endforeach</div><form method="POST" action="{{ route('owner.catalogue.price-levels.store') }}" class="mt-5 flex flex-col gap-3 sm:flex-row">@csrf<input name="name" required class="rounded-xl border-slate-200" placeholder="{{ __('catalogue.level_name') }}"><input name="code" required class="rounded-xl border-slate-200" placeholder="{{ __('catalogue.code') }}"><button class="rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white">{{ __('catalogue.add_level') }}</button></form></div>
            @foreach($products as $product)
                <article id="product-{{ $product->public_id }}" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                    <div class="flex items-center justify-between"><div class="flex items-center gap-3">@if($product->image_path)<img src="{{ Storage::url($product->image_path) }}" alt="{{ $product->name }}" class="h-14 w-14 rounded-xl object-cover">@else<span class="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-100 text-slate-400">◇</span>@endif<div><h2 class="font-bold">{{ $product->name }}</h2><p class="font-mono text-xs text-slate-500">{{ $product->sku }}</p></div></div><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $product->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $product->is_active ? __('catalogue.active') : __('catalogue.inactive') }}</span></div>
                    <form method="POST" action="{{ route('owner.catalogue.products.picture', $product) }}" enctype="multipart/form-data" class="mt-4 flex flex-col gap-3 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-end">@csrf @method('PUT')<label class="flex-1 text-sm font-semibold">Product picture <span class="font-normal text-slate-400">JPG, PNG or WebP · max 4 MB</span><input type="file" name="picture" accept="image/jpeg,image/png,image/webp" required class="mt-2 block w-full rounded-xl border bg-white p-2 text-sm"></label><button class="rounded-xl border border-blue-200 bg-white px-5 py-2.5 text-sm font-bold text-blue-700">{{ $product->image_path ? 'Replace picture' : 'Add picture' }}</button></form>
                    <details class="mt-4 rounded-2xl border border-slate-200 p-4"><summary class="cursor-pointer text-sm font-bold text-blue-700">{{ __('catalogue.edit_product') }}</summary><form method="POST" action="{{ route('owner.catalogue.products.update', $product) }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf @method('PUT')<input name="name" value="{{ $product->name }}" required class="rounded-xl border-slate-200" aria-label="{{ __('catalogue.product_name') }}"><input name="sku" value="{{ $product->sku }}" required class="rounded-xl border-slate-200" aria-label="{{ __('catalogue.sku') }}"><input name="barcode" value="{{ $product->barcode }}" class="rounded-xl border-slate-200" placeholder="{{ __('catalogue.barcode') }}"><select name="category_id" class="rounded-xl border-slate-200"><option value="">{{ __('catalogue.no_category') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($product->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select><select name="brand_id" class="rounded-xl border-slate-200"><option value="">{{ __('catalogue.no_brand') }}</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected($product->brand_id === $brand->id)>{{ $brand->name }}</option>@endforeach</select><div class="flex items-center gap-4 text-xs"><label><input type="checkbox" name="is_stock_tracked" value="1" @checked($product->is_stock_tracked)> {{ __('catalogue.stock_tracked') }}</label><label><input type="checkbox" name="tracks_expiry" value="1" @checked($product->tracks_expiry)> {{ __('catalogue.expiry') }}</label></div><textarea name="description" class="rounded-xl border-slate-200 md:col-span-2" placeholder="{{ __('catalogue.description') }}">{{ $product->description }}</textarea><button class="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">{{ __('catalogue.save_details') }}</button></form><form method="POST" action="{{ route('owner.catalogue.products.active', $product) }}" class="mt-4 flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row">@csrf @method('PUT')<input type="hidden" name="is_active" value="{{ $product->is_active ? 0 : 1 }}"><input name="reason" required class="flex-1 rounded-xl border-slate-200" placeholder="{{ __('catalogue.activation_reason', ['action' => $product->is_active ? __('catalogue.deactivation') : __('catalogue.activation')]) }}"><button class="rounded-xl px-5 py-2.5 text-sm font-bold {{ $product->is_active ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700' }}">{{ $product->is_active ? __('catalogue.deactivate_product') : __('catalogue.activate_product') }}</button></form></details>
                    <div class="mt-5 grid gap-5 lg:grid-cols-3">
                        <form method="POST" action="{{ route('owner.catalogue.product-units.store', $product) }}" class="space-y-3 rounded-2xl bg-slate-50 p-4">@csrf<h3 class="text-sm font-bold">{{ __('catalogue.alternative_unit') }}</h3><select name="unit_id" required class="block w-full rounded-xl border-slate-200"><option value="">{{ __('catalogue.select_unit') }}</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }} ({{ $unit->symbol }})</option>@endforeach</select><input name="conversion_factor" required type="number" min="0.000001" step="0.000001" class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.factor') }}"><div class="flex gap-4 text-xs"><label><input type="checkbox" name="can_purchase" value="1" checked> {{ __('catalogue.purchase') }}</label><label><input type="checkbox" name="can_sell" value="1" checked> {{ __('catalogue.sale') }}</label></div><button class="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">{{ __('catalogue.save_unit') }}</button></form>
                        <form method="POST" action="{{ route('owner.catalogue.prices.store', $product) }}" class="space-y-3 rounded-2xl bg-slate-50 p-4">@csrf<h3 class="text-sm font-bold">{{ __('catalogue.selling_price') }}</h3><select name="product_unit_id" required class="block w-full rounded-xl border-slate-200">@foreach($product->productUnits as $pu)<option value="{{ $pu->id }}">{{ $pu->unit->name }}</option>@endforeach</select><select name="price_level_id" required class="block w-full rounded-xl border-slate-200">@foreach($priceLevels as $level)<option value="{{ $level->id }}">{{ $level->name }}</option>@endforeach</select><input name="amount" required type="number" min="0" step="0.01" class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.amount') }}"><input name="reason" required class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.reason') }}"><button class="w-full rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">{{ __('catalogue.save_price') }}</button></form>
                        @if($branch)<form method="POST" action="{{ route('owner.catalogue.minimum-stock.store', $product) }}" class="space-y-3 rounded-2xl bg-slate-50 p-4">@csrf @method('PUT')<h3 class="text-sm font-bold">{{ __('catalogue.branch_minimum', ['branch' => $branch->name]) }}</h3><p class="text-xs text-slate-500">{{ __('catalogue.threshold_help') }}</p><input name="minimum_stock" required type="number" min="0" step="0.0001" class="block w-full rounded-xl border-slate-200" placeholder="{{ __('catalogue.base_quantity') }}"><button class="w-full rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-bold text-blue-700">{{ __('catalogue.save_threshold') }}</button></form>@else<div class="rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">{{ __('catalogue.select_branch') }}</div>@endif
                    </div>
                </article>
            @endforeach
        </section>
    </div>
</x-app-layout>
