@props(['sale', 'business', 'branch', 'accounts', 'template' => 'classic'])
@php
    $customer = $sale->customer;
    $customerName = $customer?->name ?? $sale->walk_in_name ?? 'Walk-in customer';
    $customerPhone = $customer?->phone ?? $sale->walk_in_phone;
    $confirmed = $sale->paymentAllocations->filter(fn ($allocation) => $allocation->payment?->status?->value === 'confirmed');
    $paid = (float) $confirmed->sum('amount'); $balance = max(0, (float) $sale->total_amount - $paid);
    $label = $sale->status->value === 'draft' ? 'DRAFT' : ($sale->payment_status->value === 'paid' ? 'PAID' : ($sale->payment_status->value === 'partially_paid' ? 'PART PAID' : 'UNPAID'));
    $accent = $label === 'PAID' ? 'emerald' : ($label === 'DRAFT' ? 'slate' : 'red');
@endphp
<div @class(['mx-auto max-w-5xl text-slate-800', 'rounded-2xl border border-slate-200 p-4 sm:p-8' => $template !== 'modern', 'overflow-hidden rounded-2xl border border-slate-200' => $template === 'modern', 'max-w-3xl text-sm' => $template === 'compact'])>
    <div @class(['flex flex-col justify-between gap-6 border-b pb-6 sm:flex-row', 'bg-slate-950 px-5 py-6 text-white sm:px-8' => $template === 'modern', 'p-5' => $template !== 'modern'])>
        <div><p class="text-2xl font-black tracking-tight">{{ $business->name }}</p><p class="mt-1 text-xs opacity-70">HardFlow · {{ $branch->name }}</p><div class="mt-3 text-sm leading-6 opacity-80">{{ $business->address ?: $branch->address }}<br>{{ $business->phone ?: $branch->phone }} {{ $business->email ? '· '.$business->email : '' }}</div></div>
        <div class="sm:text-right"><p @class(['text-xl font-black', 'text-emerald-600'=>$accent==='emerald', 'text-red-600'=>$accent==='red', 'text-slate-600'=>$accent==='slate', 'text-emerald-300'=>$template==='modern' && $accent==='emerald', 'text-red-300'=>$template==='modern' && $accent==='red', 'text-slate-300'=>$template==='modern' && $accent==='slate'])>{{ $label }}</p><p class="mt-1 text-sm opacity-80">Due: {{ $sale->due_date?->format('l, d F Y') ?? 'On receipt' }}</p><p class="mt-4 text-2xl font-black">INVOICE</p><p class="font-bold opacity-80">#{{ $sale->sale_number }}</p></div>
    </div>
    <div class="grid gap-6 py-6 sm:grid-cols-2"><div><p class="text-xs font-black uppercase tracking-wider text-slate-500">Invoiced to</p><p class="mt-2 font-bold text-slate-950">{{ $customerName }}</p><div class="mt-1 text-sm leading-6 text-slate-600">{{ $customerPhone }}<br>{{ $customer?->email }}<br>{{ $customer?->location }}</div></div><div class="sm:text-right"><p class="text-xs font-black uppercase tracking-wider text-slate-500">Pay to</p><p class="mt-2 font-bold text-slate-950">{{ $business->name }}</p><div class="mt-1 text-sm leading-6 text-slate-600">{{ $business->address ?: $branch->address }}<br>{{ $business->phone ?: $branch->phone }}<br>{{ $business->tin ? 'TIN: '.$business->tin : '' }}</div></div></div>
    <div class="mb-6 grid gap-3 border-y py-4 text-sm sm:grid-cols-3"><div><span class="block text-xs font-bold uppercase text-slate-500">Invoice date</span>{{ $sale->sale_date?->format('l, d F Y') }}</div><div><span class="block text-xs font-bold uppercase text-slate-500">Payment status</span>{{ str($sale->payment_status->value)->replace('_', ' ')->title() }}</div><div><span class="block text-xs font-bold uppercase text-slate-500">Goods stage</span>{{ str($sale->fulfillment_status->value)->replace('_', ' ')->title() }}</div></div>
    <div class="overflow-x-auto rounded-xl border"><table class="w-full min-w-[620px] text-sm"><thead @class(['bg-slate-100 text-slate-900'=>$template!=='modern', 'bg-blue-700 text-white'=>$template==='modern'])><tr><th class="p-3 text-left">Product details</th><th class="p-3 text-right">Qty</th><th class="p-3 text-right">Unit price</th><th class="p-3 text-right">Discount</th><th class="p-3 text-right">Amount</th></tr></thead><tbody>@foreach($sale->items as $item)<tr class="border-t"><td class="p-3 font-semibold">{{ $item->product?->name ?? 'Product removed' }}<span class="ml-1 text-xs font-normal text-slate-500">{{ $item->productUnit?->unit?->symbol }}</span></td><td class="p-3 text-right">{{ rtrim(rtrim(number_format((float)$item->quantity, 4), '0'), '.') }}</td><td class="p-3 text-right">{{ $business->currency }} {{ number_format((float)$item->applied_unit_price, 2) }}</td><td class="p-3 text-right">{{ $business->currency }} {{ number_format((float)$item->discount_amount, 2) }}</td><td class="p-3 text-right font-bold">{{ $business->currency }} {{ number_format((float)$item->line_total, 2) }}</td></tr>@endforeach</tbody></table></div>
    <div class="ml-auto mt-4 max-w-sm space-y-2 text-sm"><div class="flex justify-between"><span>Subtotal</span><span>{{ $business->currency }} {{ number_format((float)$sale->subtotal, 2) }}</span></div><div class="flex justify-between"><span>Discount</span><span>{{ $business->currency }} {{ number_format((float)$sale->discount_amount, 2) }}</span></div><div class="flex justify-between border-t pt-2 text-lg font-black"><span>Total</span><span>{{ $business->currency }} {{ number_format((float)$sale->total_amount, 2) }}</span></div><div class="flex justify-between text-emerald-700"><span>Paid</span><span>{{ $business->currency }} {{ number_format($paid, 2) }}</span></div><div class="flex justify-between border-t pt-2 font-black"><span>Balance</span><span>{{ $business->currency }} {{ number_format($balance, 2) }}</span></div></div>
    <div class="mt-8 grid gap-5 border-t pt-5 sm:grid-cols-2"><div><p class="text-xs font-black uppercase tracking-wider text-slate-500">Payment details</p><div class="mt-2 space-y-2 text-sm">@forelse($accounts as $account)<div class="rounded-lg bg-slate-50 p-2.5"><strong>{{ $account->method->name }} · {{ $account->name }}</strong><span class="block text-slate-600">{{ $account->account_reference ?: 'Contact the business for account details.' }}</span></div>@empty<p class="text-slate-500">Payment details will be provided by {{ $business->name }}.</p>@endforelse</div></div><div><p class="text-xs font-black uppercase tracking-wider text-slate-500">Payment transactions</p><div class="mt-2 space-y-2 text-sm">@forelse($confirmed as $allocation)<div class="flex justify-between rounded-lg bg-slate-50 p-2.5"><span>{{ $allocation->payment->payment_date?->format('d M Y') }} · {{ $allocation->payment->account?->method?->name }}<small class="block text-slate-500">{{ $allocation->payment->external_reference }}</small></span><strong>{{ $business->currency }} {{ number_format((float)$allocation->amount, 2) }}</strong></div>@empty<p class="text-slate-500">No related payments have been recorded.</p>@endforelse</div></div></div>
</div>
