<x-app-layout>
    <x-slot name="header">
        <p class="text-xs font-bold uppercase tracking-widest text-blue-700">{{ $business->name }} · {{ $branch->name }}</p>
        <h1 class="mt-1 text-2xl font-bold">{{ __('purchases.title') }}</h1>
        <p class="mt-1 text-sm text-slate-500">{{ __('purchases.subtitle') }}</p>
    </x-slot>

    <div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8" x-data="{ tab: @js(in_array(request('tab'), ['orders','new','suppliers','returns','ledger'], true) ? request('tab') : 'orders'), lines: [0] }">
        @if(session('status'))<div class="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif

        <div class="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">
            @foreach(__('purchases.tabs') as $key => $label)
                <button type="button" @click="tab='{{ $key }}'" :class="tab === '{{ $key }}' ? 'bg-blue-700 text-white' : 'text-slate-600'" class="rounded-xl px-5 py-3 text-sm font-bold">{{ $label }}</button>
            @endforeach
        </div>

        <section x-show="tab === 'new'" x-cloak class="rounded-3xl border bg-white p-6 shadow-sm">
            <h2 class="text-lg font-bold">{{ __('purchases.create_draft') }}</h2>
            <form method="POST" action="{{ route('owner.purchases.store') }}" class="mt-5 space-y-5">@csrf
                <div class="grid gap-4 md:grid-cols-3">
                    <select name="supplier_id" class="rounded-xl border-slate-200"><option value="">{{ __('purchases.supplier_optional') }}</option>@foreach($suppliers->where('is_active', true) as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select>
                    <input name="purchase_date" type="date" value="{{ now()->toDateString() }}" required class="rounded-xl border-slate-200">
                    <input name="supplier_reference" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.supplier_reference') }}">
                </div>
                <template x-for="(line, index) in lines" :key="line"><div class="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[2fr_1fr_1fr_auto]">
                    <select :name="`items[${index}][product_unit_id]`" required class="rounded-xl border-slate-200"><option value="">{{ __('purchases.product_unit') }}</option>@foreach($products as $product)@foreach($product->productUnits as $productUnit)<option value="{{ $productUnit->id }}">{{ $product->name }} · {{ $productUnit->unit->symbol }} (×{{ $productUnit->conversion_factor }})</option>@endforeach @endforeach</select>
                    <input :name="`items[${index}][quantity]`" type="number" min="0.0001" step="0.0001" required class="rounded-xl border-slate-200" placeholder="{{ __('purchases.quantity') }}">
                    <input :name="`items[${index}][unit_cost]`" type="number" min="0" step="0.01" required class="rounded-xl border-slate-200" placeholder="{{ __('purchases.unit_cost') }}">
                    <button x-show="lines.length > 1" type="button" @click="lines.splice(index, 1)" class="rounded-xl px-3 text-sm font-bold text-rose-600">{{ __('purchases.remove') }}</button>
                </div></template>
                <div class="flex justify-between"><button type="button" @click="lines.push(Date.now())" class="rounded-xl bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700">+ {{ __('purchases.add_line') }}</button><button class="rounded-xl bg-blue-700 px-6 py-3 font-bold text-white">{{ __('purchases.save_draft') }}</button></div>
            </form>
        </section>

        <section x-show="tab === 'suppliers'" x-cloak class="grid gap-6 lg:grid-cols-2">
            <form method="POST" action="{{ route('owner.purchases.suppliers.store') }}" class="rounded-3xl border bg-white p-6 shadow-sm">@csrf
                <h2 class="text-lg font-bold">{{ __('purchases.add_supplier') }}</h2><div class="mt-5 grid gap-4">
                    <input name="name" required class="rounded-xl border-slate-200" placeholder="{{ __('purchases.supplier_name') }}"><input name="phone" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.phone') }}"><input name="email" type="email" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.email') }}"><input name="tin" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.tin') }}"><textarea name="location" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.location') }}"></textarea><button class="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{{ __('purchases.create_supplier') }}</button>
                </div>
            </form>
            <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">{{ __('purchases.supplier_directory') }}</h2><div class="mt-4 divide-y">@forelse($suppliers as $supplier)<div class="py-4"><div class="flex justify-between gap-3"><div><p class="font-bold">{{ $supplier->name }}</p><p class="text-sm text-slate-500">{{ $supplier->phone ?: __('purchases.no_phone') }} · {{ $supplier->tin ?: __('purchases.no_tin') }}</p></div><p class="font-mono font-bold text-blue-700">{{ $business->currency }} {{ number_format((float)$supplierBalances[$supplier->id], 2) }}</p></div><form method="POST" action="{{ route('owner.purchases.suppliers.payments.store', $supplier) }}" class="mt-3 grid gap-2 sm:grid-cols-[1fr_2fr_auto]">@csrf<input name="amount" type="number" min="0.01" step="0.01" required class="rounded-xl border-slate-200 text-sm" placeholder="{{ __('purchases.payment_amount') }}"><input name="notes" required class="rounded-xl border-slate-200 text-sm" placeholder="{{ __('purchases.payment_reference') }}"><button class="rounded-xl bg-slate-900 px-4 text-sm font-bold text-white">{{ __('purchases.record_payment') }}</button></form></div>@empty<p class="py-8 text-center text-slate-500">{{ __('purchases.no_suppliers') }}</p>@endforelse</div></div>
        </section>

        <section x-show="tab === 'orders'" class="space-y-5">
            @forelse($purchases as $purchase)
                <article class="rounded-3xl border bg-white p-6 shadow-sm">
                    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-blue-700">{{ $purchase->purchase_number }}</p><h2 class="mt-1 text-lg font-bold">{{ $purchase->supplier?->name ?? __('purchases.unspecified_supplier') }}</h2><p class="text-sm text-slate-500">{{ $purchase->purchase_date->format('d M Y') }} · {{ $business->currency }} {{ number_format((float)$purchase->total_amount, 2) }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase text-slate-700">{{ str($purchase->status->value)->replace('_', ' ') }}</span></div>
                    <div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="text-xs uppercase text-slate-400"><tr><th class="py-2">{{ __('purchases.product') }}</th><th>{{ __('purchases.ordered') }}</th><th>{{ __('purchases.received') }}</th><th>{{ __('purchases.unit_cost') }}</th></tr></thead><tbody class="divide-y">@foreach($purchase->items as $item)<tr><td class="py-3 font-semibold">{{ $item->product->name }} · {{ $item->productUnit->unit->symbol }}</td><td>{{ $item->ordered_quantity }}</td><td>{{ $item->received_quantity }}</td><td>{{ number_format((float)$item->unit_cost, 2) }}</td></tr>@endforeach</tbody></table></div>
                    @if($purchase->status === \App\Enums\PurchaseStatus::Draft)<form method="POST" action="{{ route('owner.purchases.order', $purchase) }}" class="mt-4">@csrf<button class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{{ __('purchases.mark_ordered') }}</button></form>@endif
                    @if(in_array($purchase->status, [\App\Enums\PurchaseStatus::Ordered, \App\Enums\PurchaseStatus::PartiallyReceived], true))
                        <form method="POST" action="{{ route('owner.purchases.receipts.store', $purchase) }}" class="mt-5 rounded-2xl border border-blue-100 bg-blue-50/40 p-4">@csrf<h3 class="font-bold">{{ __('purchases.record_delivery') }}</h3><input type="hidden" name="received_at" value="{{ now()->toDateTimeString() }}">
                            <div class="mt-3 space-y-3">@foreach($purchase->items as $index => $item)@php($outstanding = bcsub((string)$item->ordered_quantity, (string)$item->received_quantity, 4))@if(bccomp($outstanding, '0', 4) > 0)<div class="grid gap-3 md:grid-cols-4"><input type="hidden" name="items[{{ $index }}][purchase_item_id]" value="{{ $item->id }}"><label class="text-sm font-semibold">{{ $item->product->name }}<span class="block text-xs font-normal text-slate-500">{{ __('purchases.outstanding', ['quantity' => $outstanding]) }}</span></label><input name="items[{{ $index }}][received_quantity]" value="{{ $outstanding }}" type="number" min="0.0001" max="{{ $outstanding }}" step="0.0001" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.received') }}"><input name="items[{{ $index }}][damaged_quantity]" value="0" type="number" min="0" step="0.0001" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.damaged') }}"><input name="items[{{ $index }}][difference_reason]" class="rounded-xl border-slate-200" placeholder="{{ __('purchases.partial_reason') }}"></div>@endif @endforeach</div>
                            <button class="mt-4 rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white">{{ __('purchases.save_receipt') }}</button>
                        </form>
                    @endif
                    @foreach($purchase->receipts as $receipt)<div class="mt-4 flex flex-wrap items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p class="font-bold">{{ $receipt->receipt_number }}</p><p class="text-xs text-slate-500">{{ $receipt->status->value }} · {{ __('purchases.lines', ['count' => $receipt->items->count()]) }}</p></div>@if($receipt->status === \App\Enums\GoodsReceiptStatus::Draft)<form method="POST" action="{{ route('owner.purchases.receipts.confirm', $receipt) }}">@csrf<button class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">{{ __('purchases.confirm_inventory') }}</button></form>@endif</div>@endforeach
                    @if($purchase->supplier && in_array($purchase->status, [\App\Enums\PurchaseStatus::PartiallyReceived, \App\Enums\PurchaseStatus::Received], true))<form method="POST" action="{{ route('owner.purchases.returns.store', $purchase) }}" class="mt-4 grid gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 md:grid-cols-4">@csrf<select name="items[0][purchase_item_id]" required class="rounded-xl border-amber-200"><option value="">{{ __('purchases.item_to_return') }}</option>@foreach($purchase->items as $item)<option value="{{ $item->id }}">{{ $item->product->name }}</option>@endforeach</select><select name="items[0][stock_status]" class="rounded-xl border-amber-200"><option value="available">{{ __('purchases.available') }}</option><option value="damaged">{{ __('purchases.damaged') }}</option></select><input name="items[0][quantity]" type="number" min="0.0001" step="0.0001" required class="rounded-xl border-amber-200" placeholder="{{ __('purchases.base_quantity') }}"><input name="reason" required minlength="10" class="rounded-xl border-amber-200" placeholder="{{ __('purchases.return_reason') }}"><button class="rounded-xl bg-amber-600 px-5 py-3 text-sm font-bold text-white md:col-span-4">{{ __('purchases.request_return') }}</button></form>@endif
                </article>
            @empty<div class="rounded-3xl border bg-white p-12 text-center text-slate-500">{{ __('purchases.no_orders') }}</div>@endforelse
        </section>

        <section x-show="tab === 'returns'" x-cloak class="space-y-4">
            @forelse($returns as $return)<article class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><div><p class="text-xs font-bold uppercase text-amber-700">{{ $return->return_number }}</p><h2 class="font-bold">{{ $return->supplier->name }}</h2><p class="text-sm text-slate-500">{{ __('purchases.requested_by', ['name' => $return->requester->name]) }} · {{ $business->currency }} {{ number_format((float)$return->total_amount, 2) }}</p></div><span class="text-sm font-bold uppercase">{{ $return->status->value }}</span></div><p class="mt-3 text-sm">{{ $return->reason }}</p><div class="mt-3 text-sm text-slate-600">@foreach($return->items as $item)<span class="mr-4">{{ $item->product->name }} · {{ $item->quantity }} {{ $item->stock_status->label() }}</span>@endforeach</div>@if($return->status === \App\Enums\SupplierReturnStatus::Pending && $return->requested_by !== auth()->id())<form method="POST" action="{{ route('owner.purchases.returns.decision', $return) }}" class="mt-4 flex gap-3">@csrf @method('PUT')<input name="reason" required class="flex-1 rounded-xl border-slate-200" placeholder="{{ __('purchases.decision_evidence') }}"><button name="decision" value="approve" class="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">{{ __('purchases.approve') }}</button><button name="decision" value="reject" class="rounded-xl bg-rose-50 px-4 py-2 font-bold text-rose-700">{{ __('purchases.reject') }}</button></form>@endif</article>@empty<div class="rounded-3xl border bg-white p-12 text-center text-slate-500">{{ __('purchases.no_returns') }}</div>@endforelse
        </section>

        <section x-show="tab === 'ledger'" x-cloak class="overflow-x-auto rounded-3xl border bg-white shadow-sm"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">{{ __('purchases.date') }}</th><th>{{ __('purchases.supplier') }}</th><th>{{ __('purchases.type') }}</th><th>{{ __('purchases.debit') }}</th><th>{{ __('purchases.credit') }}</th><th>{{ __('purchases.notes') }}</th></tr></thead><tbody class="divide-y">@forelse($ledgerEntries as $entry)<tr><td class="p-4">{{ $entry->occurred_at->format('d M Y H:i') }}</td><td class="font-semibold">{{ $entry->supplier->name }}</td><td>{{ str($entry->entry_type->value)->replace('_', ' ')->headline() }}</td><td class="font-mono">{{ $entry->debit }}</td><td class="font-mono">{{ $entry->credit }}</td><td class="pr-4 text-slate-500">{{ $entry->notes }}</td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-500">{{ __('purchases.no_ledger') }}</td></tr>@endforelse</tbody></table></section>
    </div>
</x-app-layout>
