@if($dashboardLayout === 'smartflow')
<section class="hardflow-smartart overflow-hidden rounded-3xl border border-blue-100 bg-gradient-to-br from-white via-blue-50/40 to-slate-50 p-4 shadow-sm sm:p-5">
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{{ __('dashboard.smartart_title') }}</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ __('dashboard.business_flow') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('dashboard.smartart_help') }}</p></div><span class="rounded-full border border-blue-200 bg-white px-3 py-1.5 text-xs font-bold text-blue-700">{{ trans_choice('dashboard.available_modules', $dashboardModules->count(), ['count' => $dashboardModules->count()]) }}</span></div>
    <div class="flex min-w-max snap-x snap-mandatory items-stretch gap-3 overflow-x-auto pb-3 lg:min-w-0">
        @foreach($dashboardModules->groupBy('group') as $group => $modules)
            <div class="flex items-center gap-3"><div class="w-56 shrink-0 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p class="mb-2 border-b pb-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{{ $group }}</p><div class="space-y-2">@foreach($modules as $module)<a href="{{ route($module['route']) }}" class="group flex items-center gap-3 rounded-xl border border-transparent bg-slate-50 px-3 py-2.5 transition hover:border-blue-200 hover:bg-blue-50"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-700 text-[11px] font-black text-white">{{ $module['icon'] }}</span><span class="min-w-0 flex-1 truncate text-sm font-bold text-slate-800 group-hover:text-blue-800">{{ $module['label'] }}</span><span class="text-blue-500">›</span></a>@endforeach</div></div>@unless($loop->last)<div class="flex w-10 shrink-0 items-center"><span class="h-px flex-1 bg-blue-300"></span><span class="text-xl text-blue-600">→</span></div>@endunless</div>
        @endforeach
    </div>
</section>
@elseif($dashboardLayout === 'cards')
@php
    $moduleGroups = $dashboardModules->groupBy('group');
    $children = [
        'owner.sales.index' => [['New sale', ['screen' => 'pos']], ['Sales & documents', ['screen' => 'history']], ['Fulfillment & returns', ['screen' => 'fulfillment']], ['Customers', ['screen' => 'customers']]],
        'owner.catalogue.index' => [['Products', ['panel' => 'products']], ['Catalogue setup', ['panel' => 'setup']], ['Pricing', ['panel' => 'pricing']]],
        'owner.inventory.index' => [['Stock balances', ['tab' => 'balances']], ['Opening stock', ['tab' => 'opening']], ['Adjustments', ['tab' => 'adjust']], ['Stock counts', ['tab' => 'counts']], ['Movements', ['tab' => 'movements']]],
        'owner.purchases.index' => [['Orders', ['tab' => 'orders']], ['New purchase', ['tab' => 'new']], ['Suppliers', ['tab' => 'suppliers']], ['Returns', ['tab' => 'returns']], ['Supplier ledger', ['tab' => 'ledger']]],
        'owner.payments.index' => [['Debts', ['tab' => 'debts']], ['Payment history', ['tab' => 'history']], ['Accounts', ['tab' => 'accounts']], ['Transfers', ['tab' => 'transfers']], ['Cash sessions', ['tab' => 'cash']]],
    ];
@endphp
<section class="rounded-3xl border bg-white p-4 shadow-sm sm:p-5" x-data="{ openGroup: @js($moduleGroups->keys()->first()) }">
    <div class="flex items-center gap-2 overflow-x-auto pb-3">@foreach($moduleGroups as $group => $modules)<button type="button" @click="openGroup=@js($group)" :class="openGroup===@js($group)?'border-blue-700 bg-blue-700 text-white':'border-slate-200 bg-white text-slate-700'" class="flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><span class="flex h-6 w-6 items-center justify-center rounded-lg bg-slate-100/20">{{ $modules->first()['icon'] }}</span>{{ $group }}<span>⌄</span></button>@endforeach</div>
    <div class="space-y-2 border-t pt-4">@foreach($moduleGroups as $group => $modules)<div x-show="openGroup===@js($group)" x-cloak class="space-y-2">@foreach($modules as $module)<details class="group rounded-xl border border-slate-200 bg-slate-50"><summary class="flex cursor-pointer list-none items-center gap-3 px-4 py-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-700 text-xs font-black text-white">{{ $module['icon'] }}</span><span class="flex-1 font-bold">{{ $module['label'] }}</span><span class="text-slate-400 transition group-open:rotate-180">⌄</span></summary><div class="grid gap-2 border-t border-slate-200 bg-white p-3 sm:grid-cols-2 lg:grid-cols-4">@forelse($children[$module['route']] ?? [] as [$childLabel,$parameters])<a href="{{ route($module['route'], $parameters) }}" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:bg-blue-50 hover:text-blue-800">{{ $childLabel }} <span class="float-right">›</span></a>@empty<a href="{{ route($module['route']) }}" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:bg-blue-50 hover:text-blue-800">Open {{ $module['label'] }} <span class="float-right">›</span></a>@endforelse</div></details>@endforeach</div>@endforeach</div>
</section>
<section class="hidden rounded-3xl border bg-white p-5 shadow-sm">
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{{ __('dashboard.cards_title') }}</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ __('dashboard.all_components') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('dashboard.cards_help_text') }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">{{ trans_choice('dashboard.available_modules', $dashboardModules->count(), ['count' => $dashboardModules->count()]) }}</span></div>
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">@foreach($dashboardModules as $module)<a href="{{ route($module['route']) }}" class="group rounded-2xl border border-slate-200 p-4 transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div class="flex items-start justify-between"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-sm font-black text-blue-700 group-hover:bg-blue-700 group-hover:text-white">{{ $module['icon'] }}</span><span class="text-slate-300 group-hover:text-blue-600">↗</span></div><h3 class="mt-4 font-black text-slate-900">{{ $module['label'] }}</h3><p class="mt-1 text-xs font-semibold uppercase tracking-wide text-slate-400">{{ $module['group'] }}</p></a>@endforeach</div>
</section>
@endif
