<x-app-layout>
    <x-slot name="header"><div class="flex items-center gap-3"><a href="{{ route('owner.expenses.index') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm hover:border-blue-300 hover:bg-blue-50">← Back</a><div><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-700">{{ __('expenses.new_eyebrow') }}</p><h1 class="mt-1 text-2xl font-black text-slate-950">{{ __('expenses.new_title') }}</h1><p class="mt-1 text-sm text-slate-500">{{ __('expenses.new_subtitle') }}</p></div></div></x-slot>

    <form method="POST" action="{{ route('owner.expenses.store') }}" x-data="{ amount: '{{ old('amount') }}', account: '{{ old('payment_account_id') }}' }" class="py-6">@csrf
        @if($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{{ $errors->first() }}</div>@endif
        <div class="grid gap-5 lg:grid-cols-3">
            <div class="space-y-5 lg:col-span-2">
                <section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="mb-5 border-b pb-3"><h2 class="font-bold text-slate-900">{{ __('expenses.details') }}</h2><p class="text-xs text-slate-500">{{ __('expenses.details_help') }}</p></div>
                    <div class="grid gap-4 sm:grid-cols-2">
                        <label class="text-sm font-semibold sm:col-span-2">{{ __('expenses.expense_title') }} <span class="text-rose-500">*</span><input name="title" value="{{ old('title') }}" required placeholder="{{ __('expenses.title_example') }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label>
                        <label class="text-sm font-semibold">{{ __('expenses.category') }} <span class="text-rose-500">*</span><select name="expense_category_id" required class="mt-1.5 w-full rounded-xl border-slate-300"><option value="">{{ __('expenses.select_category') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('expense_category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
                        <label class="text-sm font-semibold">{{ __('expenses.expense_date') }} <span class="text-rose-500">*</span><input type="date" name="expense_date" value="{{ old('expense_date',now()->toDateString()) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label>
                        <label class="text-sm font-semibold">{{ __('expenses.vendor_payee') }}<input name="vendor" value="{{ old('vendor') }}" placeholder="{{ __('expenses.vendor_placeholder') }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label>
                        <label class="text-sm font-semibold">{{ __('expenses.receipt_reference') }}<input name="receipt_reference" value="{{ old('receipt_reference') }}" placeholder="{{ __('expenses.receipt_placeholder') }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label>
                        <label class="text-sm font-semibold sm:col-span-2">{{ __('expenses.description') }}<textarea name="description" rows="3" placeholder="{{ __('expenses.description_placeholder') }}" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('description') }}</textarea></label>
                    </div>
                </section>

                <section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="mb-5 border-b pb-3"><h2 class="font-bold text-slate-900">{{ __('expenses.amount_account') }}</h2><p class="text-xs text-slate-500">{{ __('expenses.amount_help') }}</p></div>
                    <label class="block text-sm font-semibold">{{ __('expenses.amount_currency', ['currency' => $business->currency]) }} <span class="text-rose-500">*</span><div class="relative mt-1.5"><span class="absolute left-3 top-2.5 text-sm font-bold text-slate-400">{{ $business->currency }}</span><input x-model="amount" type="number" min="0.01" step="0.01" name="amount" required class="w-full rounded-xl border-slate-300 pl-12 text-lg font-bold"></div></label>
                    <div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($accounts as $paymentAccount)<label class="cursor-pointer"><input x-model="account" type="radio" name="payment_account_id" value="{{ $paymentAccount->id }}" class="peer sr-only"><div class="rounded-xl border p-4 transition peer-checked:border-blue-600 peer-checked:bg-blue-50 peer-checked:ring-2 peer-checked:ring-blue-100"><div class="flex items-start justify-between gap-2"><div><p class="font-bold">{{ $paymentAccount->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $paymentAccount->method->name }}{{ $paymentAccount->account_reference ? ' · '.$paymentAccount->account_reference : '' }}</p></div><span class="h-3 w-3 rounded-full border-2 border-slate-300 peer-checked:border-blue-600"></span></div><p class="mt-3 text-xs text-slate-500">{{ __('expenses.available_balance') }}</p><p class="font-bold text-slate-800">{{ $business->currency }} {{ number_format($paymentAccount->current_balance,2) }}</p></div></label>@empty<div class="rounded-xl border border-dashed p-4 text-sm text-slate-500 sm:col-span-2">{{ __('expenses.no_active_account') }}</div>@endforelse</div>
                </section>

                <section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">{{ __('expenses.team_notes') }}</h2><textarea name="notes" rows="3" class="mt-3 w-full rounded-xl border-slate-300" placeholder="{{ __('expenses.optional_notes') }}">{{ old('notes') }}</textarea></section>
            </div>

            <aside class="space-y-5">
                <section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">{{ __('expenses.approval_workflow') }}</h2><div class="mt-5 space-y-0">@foreach(__('expenses.steps') as $index => [$label,$description])@php($step = (string) ($index + 1))<div class="flex gap-3"><div class="flex flex-col items-center"><span @class(['flex h-8 w-8 items-center justify-center rounded-full text-xs font-black','bg-blue-700 text-white'=>$step==='1','bg-slate-100 text-slate-400'=>$step!=='1'])>{{ $step }}</span>@if($step!=='4')<span class="h-8 w-px bg-slate-200"></span>@endif</div><div><p class="text-sm font-bold">{{ $label }}</p><p class="text-xs text-slate-500">{{ $description }}</p></div></div>@endforeach</div></section>
                <section class="rounded-2xl border border-blue-100 bg-blue-50 p-5"><p class="text-xs font-bold uppercase tracking-wider text-blue-700">{{ __('expenses.summary') }}</p><p class="mt-3 text-2xl font-black text-slate-950" x-text="@js($business->currency) + ' ' + (Number(amount || 0)).toLocaleString(undefined,{minimumFractionDigits:2})"></p><p class="mt-2 text-xs text-slate-500">{{ $business->name }} · {{ $branch->name }}</p></section>
                <section class="rounded-2xl border bg-white p-5 shadow-sm"><label class="text-sm font-semibold">{{ __('expenses.approval_reason') }}<textarea name="approval_reason" rows="3" class="mt-1.5 w-full rounded-xl border-slate-300" placeholder="{{ __('expenses.required_submitting') }}">{{ old('approval_reason') }}</textarea></label><div class="mt-4 grid gap-2"><button name="intent" value="submit" class="rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white hover:bg-blue-800">{{ __('expenses.submit_approval') }}</button><button name="intent" value="draft" class="rounded-xl border px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50">{{ __('expenses.save_draft') }}</button><a href="{{ route('owner.expenses.index') }}" class="py-2 text-center text-sm text-slate-500">{{ __('expenses.cancel') }}</a></div></section>
            </aside>
        </div>
    </form>
</x-app-layout>
