<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-blue-700">{{ __('expenses.eyebrow') }}</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ __('expenses.title') }}</h1><p class="mt-1 text-sm text-slate-500">{{ __('expenses.subtitle') }}</p></div><div class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs text-slate-500">{{ $business->name }} · {{ $branch->name }}</div></div></x-slot>

    <div class="space-y-6 py-6">
        @if (session('status')) <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div> @endif
        @if ($errors->any()) <div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{{ $errors->first() }}</div> @endif

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-slate-500">{{ __('expenses.this_month') }}</p><p class="mt-2 text-2xl font-black">{{ $business->currency }} {{ number_format($monthTotal, 2) }}</p></div>
            <div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-slate-500">{{ __('expenses.all_posted') }}</p><p class="mt-2 text-2xl font-black text-blue-700">{{ $business->currency }} {{ number_format($postedTotal, 2) }}</p></div>
            <div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wider text-slate-500">{{ __('expenses.awaiting_approval') }}</p><p class="mt-2 text-2xl font-black text-amber-600">{{ $pendingCount }}</p></div>
            <a href="{{ route('owner.expenses.create') }}" class="rounded-2xl bg-blue-700 p-5 text-left text-white shadow-sm transition hover:bg-blue-800"><p class="text-xs font-semibold uppercase tracking-wider text-blue-100">{{ __('expenses.quick_action') }}</p><p class="mt-2 text-lg font-bold">+ {{ __('expenses.record_expense') }}</p></a>
        </div>

        <div class="rounded-2xl border bg-white shadow-sm">
            <div class="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 class="font-bold">{{ __('expenses.register') }}</h2><p class="text-xs text-slate-500">{{ __('expenses.workflow_short') }}</p></div><a href="{{ route('owner.expenses.export', request()->query()) }}" class="rounded-xl border px-4 py-2 text-sm font-bold text-blue-700 hover:bg-blue-50">{{ __('expenses.export_csv') }}</a></div>
            <form class="grid gap-2 border-b bg-slate-50/60 p-4 sm:grid-cols-2 lg:grid-cols-6"><input name="search" value="{{ request('search') }}" placeholder="{{ __('expenses.search') }}" class="rounded-xl border-slate-300 text-sm"><select name="status" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('expenses.all_statuses') }}</option>@foreach(['draft','pending','approved','posted','','reversed'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><select name="category" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('expenses.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select><select name="account" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('expenses.all_accounts') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string)request('account')===(string)$account->id)>{{ $account->name }}</option>@endforeach</select><input type="date" name="from" value="{{ request('from') }}" class="rounded-xl border-slate-300 text-sm" title="{{ __('expenses.from_date') }}"><div class="flex gap-2"><input type="date" name="to" value="{{ request('to') }}" class="min-w-0 flex-1 rounded-xl border-slate-300 text-sm" title="{{ __('expenses.to_date') }}"><button class="rounded-xl bg-slate-900 px-4 text-sm font-bold text-white">{{ __('expenses.filter') }}</button></div></form>
            <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">{{ __('expenses.expense') }}</th><th class="px-5 py-3">{{ __('expenses.category_vendor') }}</th><th class="px-5 py-3">{{ __('expenses.amount') }}</th><th class="px-5 py-3">{{ __('expenses.status') }}</th><th class="px-5 py-3">{{ __('expenses.actions') }}</th></tr></thead><tbody class="divide-y">
            @forelse($expenses as $expense)<tr class="align-top hover:bg-slate-50/70"><td class="px-5 py-4"><p class="font-bold">{{ $expense->expense_number }}</p><p class="text-slate-500">{{ $expense->title }}</p><p class="mt-1 text-xs text-slate-400">{{ $expense->expense_date->format('d M Y') }}</p></td><td class="px-5 py-4"><p>{{ $expense->category->name }}</p><p class="text-xs text-slate-500">{{ $expense->vendor ?: __('expenses.no_vendor') }}</p></td><td class="px-5 py-4 font-bold">{{ $business->currency }} {{ number_format($expense->amount, 2) }}<p class="text-xs font-normal text-slate-500">{{ $expense->account?->name ?: __('expenses.account_not_selected') }}</p></td><td class="px-5 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold','bg-slate-100 text-slate-700'=>$expense->status->value==='draft','bg-amber-100 text-amber-800'=>$expense->status->value==='pending','bg-blue-100 text-blue-800'=>$expense->status->value==='approved','bg-emerald-100 text-emerald-800'=>$expense->status->value==='posted','bg-rose-100 text-rose-800'=>$expense->status->value==='reversed'])>{{ ucfirst($expense->status->value) }}</span></td><td class="px-5 py-4"><div class="space-y-2">
                @if($expense->status->value === 'draft')<form method="POST" action="{{ route('owner.expenses.submit', $expense) }}" class="flex gap-2">@csrf<input name="reason" required placeholder="{{ __('expenses.reason') }}" class="w-32 rounded-lg border-slate-300 text-xs"><button class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white">{{ __('expenses.submit') }}</button></form>@endif
                @if($expense->status->value === 'pending' && ($approval = $expense->approvals->where('status.value','pending')->first()))<form method="POST" action="{{ route('owner.expenses.approvals.decision', $approval) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<input name="reason" required placeholder="{{ __('expenses.decision_note') }}" class="w-32 rounded-lg border-slate-300 text-xs"><button name="decision" value="approve" class="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">{{ __('expenses.approve') }}</button><button name="decision" value="reject" class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">{{ __('expenses.reject') }}</button></form>@endif
                @if($expense->status->value === 'approved')<form method="POST" action="{{ route('owner.expenses.post', $expense) }}">@csrf<button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">{{ __('expenses.post_payment') }}</button></form>@endif
                @if($expense->status->value === 'posted')<form method="POST" action="{{ route('owner.expenses.reverse', $expense) }}" class="flex gap-2">@csrf<input name="reason" required placeholder="{{ __('expenses.reversal_reason') }}" class="w-32 rounded-lg border-slate-300 text-xs"><button class="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">{{ __('expenses.reverse') }}</button></form>@endif
            </div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">{{ __('expenses.no_expenses') }}</td></tr>@endforelse
            </tbody></table></div>
        </div>
    </div>
</x-app-layout>
