<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-700">Operations</p><h1 class="mt-1 text-2xl font-bold">Customer panel</h1></div><a href="{{ route('owner.sales.index', ['screen' => 'customers']) }}" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">New customer</a></div>
    </x-slot>

    <div class="mx-auto max-w-[1600px] px-3 py-5 sm:px-5">
        @if(session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif

        <form method="GET" class="mb-5 flex flex-wrap gap-2 rounded-xl border bg-white p-3"><input name="search" value="{{ request('search') }}" class="min-w-52 flex-1 rounded-lg border-slate-200 text-sm" placeholder="Search customer name, phone, or email"><select name="status" onchange="this.form.submit()" class="rounded-lg border-slate-200 text-sm"><option value="">All customers</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select><select name="per_page" onchange="this.form.submit()" class="rounded-lg border-slate-200 text-sm"><option value="6" @selected(request('per_page') == 6)>6 per page</option><option value="12" @selected(request('per_page', 12) == 12)>12 per page</option><option value="24" @selected(request('per_page') == 24)>24 per page</option><option value="48" @selected(request('per_page') == 48)>48 per page</option></select><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">Search</button></form>

        <div class="grid gap-5 xl:grid-cols-[360px_1fr]">
            <aside class="rounded-xl border bg-white p-4"><div class="mb-3 flex items-center justify-between"><h2 class="font-bold">Customers</h2><span class="text-xs text-slate-500">{{ $customers->total() }} total</span></div><div class="space-y-2">@forelse($customers as $customer)@php($balance = (float) ($customer->total_debits ?? 0) - (float) ($customer->total_credits ?? 0))<a href="{{ route('owner.customers.index', array_merge(request()->except(['customer', 'page']), ['customer' => $customer->public_id])) }}" class="block rounded-lg border p-3 transition {{ $selected?->id === $customer->id ? 'border-blue-500 bg-blue-50' : 'hover:border-blue-200 hover:bg-slate-50' }}"><div class="flex justify-between gap-2"><p class="font-bold">{{ $customer->name }}</p><span class="rounded-full px-2 py-0.5 text-[10px] font-bold {{ $customer->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $customer->is_active ? 'ACTIVE' : 'INACTIVE' }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $customer->phone ?: 'No phone' }}</p><p class="mt-2 text-xs font-semibold {{ $balance > 0 ? 'text-rose-600' : 'text-slate-600' }}">Balance: {{ $business->currency }} {{ number_format($balance, 2) }}</p></a>@empty<p class="py-8 text-center text-sm text-slate-500">No customers found.</p>@endforelse</div><div class="mt-4">{{ $customers->links() }}</div></aside>

            <main>
                @if(!$selected)<div class="flex min-h-80 items-center justify-center rounded-xl border bg-white p-10 text-center text-slate-500">Select a customer to view their sales, debt, payments, and account actions.</div>@else
                    @php($debits = $selected->ledgerEntries->sum('debit'))
                    @php($credits = $selected->ledgerEntries->sum('credit'))
                    @php($balance = (float) $debits - (float) $credits)
                    <div class="grid gap-4 lg:grid-cols-3"><div class="rounded-xl border bg-white p-5 lg:col-span-2"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-xl font-bold">{{ $selected->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $selected->phone ?: 'No phone' }}{{ $selected->email ? ' · '.$selected->email : '' }}</p><p class="mt-1 text-sm text-slate-500">{{ $selected->location ?: 'No address recorded' }}</p></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $selected->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $selected->is_active ? 'ACTIVE' : 'INACTIVE' }}</span></div><div class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">Total debits</p><p class="mt-1 font-bold">{{ $business->currency }} {{ number_format((float) $debits, 2) }}</p></div><div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">Payments / credits</p><p class="mt-1 font-bold text-emerald-700">{{ $business->currency }} {{ number_format((float) $credits, 2) }}</p></div><div class="rounded-lg bg-rose-50 p-3"><p class="text-xs text-rose-700">Outstanding balance</p><p class="mt-1 font-bold text-rose-700">{{ $business->currency }} {{ number_format($balance, 2) }}</p></div></div></div>
                        <form method="POST" action="{{ route('owner.customers.active', $selected) }}" class="rounded-xl border bg-white p-5">@csrf @method('PUT')<input type="hidden" name="is_active" value="{{ $selected->is_active ? 0 : 1 }}"><h3 class="font-bold">Customer status</h3><p class="mt-1 text-sm text-slate-500">{{ $selected->is_active ? 'Deactivate to prevent new sales for this customer.' : 'Activate to allow new sales again.' }}</p><input name="reason" required minlength="10" class="mt-4 w-full rounded-lg border-slate-200 text-sm" placeholder="Reason (minimum 10 characters)"><button class="mt-2 w-full rounded-lg px-3 py-2 text-sm font-bold {{ $selected->is_active ? 'bg-rose-50 text-rose-700' : 'bg-emerald-600 text-white' }}">{{ $selected->is_active ? 'Deactivate customer' : 'Activate customer' }}</button></form></div>

                    <section class="mt-5 rounded-xl border bg-white p-5"><details><summary class="cursor-pointer font-bold text-blue-700">Edit customer details</summary><form method="POST" action="{{ route('owner.customers.update', $selected) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf @method('PUT')<input name="name" value="{{ $selected->name }}" required class="rounded-lg border-slate-200" placeholder="Name"><input name="phone" value="{{ $selected->phone }}" class="rounded-lg border-slate-200" placeholder="Phone"><input name="email" value="{{ $selected->email }}" type="email" class="rounded-lg border-slate-200" placeholder="Email"><input name="location" value="{{ $selected->location }}" class="rounded-lg border-slate-200" placeholder="Location"><label class="text-sm"><input type="checkbox" name="is_credit_customer" value="1" @checked($selected->is_credit_customer)> Credit customer</label><input name="credit_limit" value="{{ $selected->credit_limit }}" type="number" min="0" step="0.01" class="rounded-lg border-slate-200" placeholder="Credit limit"><button class="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white md:col-span-2">Save customer details</button></form></details></section>

                    <section class="mt-5 rounded-xl border bg-white p-5"><h3 class="font-bold">Sales history</h3><div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><thead class="border-b text-left text-xs uppercase text-slate-500"><tr><th class="p-2">Sale</th><th class="p-2">Date</th><th class="p-2">Status</th><th class="p-2 text-right">Total</th><th class="p-2 text-right">Paid</th><th class="p-2">Actions</th></tr></thead><tbody class="divide-y">@forelse($selected->sales as $sale)@php($paid = $sale->paymentAllocations->where('payment.status.value', 'confirmed')->sum('amount'))<tr><td class="p-2 font-bold"><a class="text-blue-700" href="{{ route('owner.sales.show', $sale) }}">{{ $sale->sale_number }}</a></td><td class="p-2">{{ $sale->sale_date->format('d M Y') }}</td><td class="p-2"><span class="text-xs font-bold uppercase">{{ $sale->status->value }}</span></td><td class="p-2 text-right">{{ $business->currency }} {{ number_format((float) $sale->total_amount, 2) }}</td><td class="p-2 text-right text-emerald-700">{{ $business->currency }} {{ number_format((float) $paid, 2) }}</td><td class="p-2">@if($sale->status === \App\Enums\SaleStatus::Draft)<details><summary class="cursor-pointer text-xs font-bold text-blue-700">Edit</summary><form method="POST" action="{{ route('owner.customers.sales.update', $sale) }}" class="mt-2 flex gap-2">@csrf @method('PUT')<input name="due_date" value="{{ $sale->due_date?->toDateString() }}" type="date" class="rounded border-slate-200 text-xs"><button class="rounded bg-blue-700 px-2 py-1 text-xs font-bold text-white">Save</button></form></details><form method="POST" action="{{ route('owner.customers.sales.destroy', $sale) }}" class="mt-2" onsubmit="return confirm('Delete this unpaid draft sale?')">@csrf @method('DELETE')<button class="text-xs font-bold text-rose-700">Delete draft</button></form>@else<a href="{{ route('owner.sales.show', $sale) }}" class="text-xs font-bold text-blue-700">View / cancel</a>@endif</td></tr>@empty<tr><td colspan="6" class="p-6 text-center text-slate-500">No sales for this customer in the selected branch.</td></tr>@endforelse</tbody></table></div></section>

                    <div class="mt-5 grid gap-5 lg:grid-cols-2"><section class="rounded-xl border bg-white p-5"><h3 class="font-bold">Payment details</h3><div class="mt-3 space-y-2">@forelse($selected->payments as $payment)<div class="flex justify-between gap-3 rounded-lg bg-slate-50 p-3 text-sm"><div><p class="font-semibold">{{ $payment->payment_number }}</p><p class="text-xs text-slate-500">{{ $payment->account->method->name }} · {{ $payment->account->name }}{{ $payment->external_reference ? ' · '.$payment->external_reference : '' }}</p></div><strong class="text-emerald-700">{{ $business->currency }} {{ number_format((float) $payment->amount, 2) }}</strong></div>@empty<p class="py-4 text-sm text-slate-500">No payments recorded.</p>@endforelse</div></section><section class="rounded-xl border bg-white p-5"><h3 class="font-bold">Debit and credit activity</h3><div class="mt-3 space-y-2">@forelse($selected->ledgerEntries as $entry)<div class="flex justify-between gap-3 rounded-lg bg-slate-50 p-3 text-sm"><div><p class="font-semibold">{{ str($entry->entry_type)->replace('_', ' ')->headline() }}</p><p class="text-xs text-slate-500">{{ $entry->reference }} · {{ $entry->occurred_at->format('d M Y H:i') }}</p></div><div class="text-right"><p class="text-rose-700">D {{ number_format((float) $entry->debit, 2) }}</p><p class="text-emerald-700">C {{ number_format((float) $entry->credit, 2) }}</p></div></div>@empty<p class="py-4 text-sm text-slate-500">No debit or credit entries.</p>@endforelse</div></section></div>
                @endif
            </main>
        </div>
    </div>
</x-app-layout>
