<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-700">{{ __('payments.eyebrow') }}</p><h1 class="mt-1 text-2xl font-bold">{{ __('payments.title') }}</h1></div><div class="rounded-lg border bg-slate-50 px-3 py-2 text-xs text-slate-500">{{ $business->name }} · {{ $branch->name }}</div></div></x-slot>

    @php($totalDebt = $customers->sum(fn($customer) => (float)($customer->ledger_debits ?? 0) - (float)($customer->ledger_credits ?? 0)))
    @php($overdue = $sales->filter(fn($sale) => $sale->due_date?->isPast())->sum(fn($sale) => (float)$sale->outstanding_amount))
    <div class="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6" x-data="payments">
        @if(session('status'))<div class="rounded-xl bg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif

        <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ __('payments.outstanding_debt') }}</p><p class="mt-1 text-xl font-bold">{{ $business->currency }} {{ number_format($totalDebt, 2) }}</p></div><div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ __('payments.overdue') }}</p><p class="mt-1 text-xl font-bold text-rose-600">{{ $business->currency }} {{ number_format($overdue, 2) }}</p></div><div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ __('payments.open_invoices') }}</p><p class="mt-1 text-xl font-bold">{{ $sales->count() }}</p></div><div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ __('payments.payments_recorded') }}</p><p class="mt-1 text-xl font-bold text-emerald-600">{{ $payments->count() }}</p></div></div>

        <div class="flex flex-wrap gap-2">@foreach(__('payments.tabs') as $key => $label)<button @click="tab='{{ $key }}'" :class="tab==='{{ $key }}'?'bg-blue-700 text-white':'bg-white text-slate-600'" class="rounded-lg border px-4 py-2 text-sm font-bold">{{ $label }}</button>@endforeach</div>

        <section x-show="tab==='debts'" class="overflow-hidden rounded-xl border bg-white"><div class="border-b p-4"><h2 class="font-bold">{{ __('payments.unpaid_invoices') }}</h2><p class="text-xs text-slate-500">{{ __('payments.allocate_help') }}</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-3">{{ __('payments.customer_invoice') }}</th><th class="p-3">{{ __('payments.due') }}</th><th class="p-3 text-right">{{ __('payments.invoice') }}</th><th class="p-3 text-right">{{ __('payments.outstanding') }}</th><th class="p-3">{{ __('payments.receive_payment') }}</th></tr></thead><tbody class="divide-y">@forelse($sales as $sale)<tr><td class="p-3"><p class="font-bold">{{ $sale->customer->name }}</p><p class="text-xs text-blue-700">{{ $sale->sale_number }}</p></td><td class="p-3"><span class="{{ $sale->due_date?->isPast() ? 'text-rose-600' : 'text-slate-500' }}">{{ $sale->due_date?->format('d M Y') ?? __('payments.not_set') }}</span></td><td class="p-3 text-right">{{ $business->currency }} {{ number_format((float)$sale->total_amount, 2) }}</td><td class="p-3 text-right font-bold text-amber-600">{{ $business->currency }} {{ number_format((float)$sale->outstanding_amount, 2) }}</td><td class="p-3"><form method="POST" action="{{ route('owner.payments.store', $sale->customer) }}" class="flex min-w-[430px] gap-2">@csrf<input type="hidden" name="allocations[0][sale_id]" value="{{ $sale->id }}"><select name="payment_account_id" required class="w-36 rounded-lg border-slate-200 text-xs"><option value="">{{ __('payments.account') }}</option>@foreach($accounts->where('is_active', true) as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input name="amount" x-ref="amount{{ $sale->id }}" type="number" step="0.01" min="0.01" max="{{ $sale->outstanding_amount }}" value="{{ $sale->outstanding_amount }}" class="w-28 rounded-lg border-slate-200 text-xs"><input name="allocations[0][amount]" type="hidden" value="{{ $sale->outstanding_amount }}" :value="$refs.amount{{ $sale->id }}.value"><input name="external_reference" class="w-32 rounded-lg border-slate-200 text-xs" placeholder="{{ __('payments.reference') }}"><button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">{{ __('payments.receive') }}</button></form></td></tr>@empty<tr><td colspan="5" class="p-12 text-center text-slate-500">{{ __('payments.no_unpaid_invoices') }}</td></tr>@endforelse</tbody></table></div></section>

        <section x-show="tab==='history'" x-cloak class="overflow-hidden rounded-xl border bg-white"><div class="border-b p-4"><h2 class="font-bold">{{ __('payments.tabs.history') }}</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-3">{{ __('payments.receipt') }}</th><th class="p-3">{{ __('payments.customer') }}</th><th class="p-3">{{ __('payments.method') }}</th><th class="p-3">{{ __('payments.reference') }}</th><th class="p-3 text-right">{{ __('payments.amount') }}</th><th class="p-3">{{ __('payments.status') }}</th></tr></thead><tbody class="divide-y">@forelse($payments as $payment)<tr><td class="p-3 font-bold text-blue-700">{{ $payment->payment_number }}</td><td class="p-3">{{ $payment->customer?->name ?? __('payments.unallocated') }}</td><td class="p-3">{{ $payment->account->method->name }}</td><td class="p-3 text-slate-500">{{ $payment->external_reference ?: __('payments.internal_cash_receipt') }}</td><td class="p-3 text-right font-bold text-emerald-600">{{ $business->currency }} {{ number_format((float)$payment->amount, 2) }}</td><td class="p-3 text-xs font-bold uppercase">{{ $payment->status->value }}</td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-500">{{ __('payments.no_payments') }}</td></tr>@endforelse</tbody></table></div></section>

        <section x-show="tab==='accounts'" x-cloak class="grid gap-5 lg:grid-cols-3"><div class="grid gap-3 sm:grid-cols-2 lg:col-span-2">@forelse($accounts as $account)<article class="rounded-xl border bg-white p-4"><div class="flex justify-between"><div><p class="font-bold">{{ $account->name }}</p><p class="text-xs text-slate-500">{{ $account->method->name }} · {{ $account->account_reference ?: __('payments.no_external_reference') }}</p></div><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{{ __('payments.active') }}</span></div><p class="mt-4 text-xs text-slate-500">{{ __('payments.confirmed_receipts') }}</p><p class="text-xl font-bold">{{ $business->currency }} {{ number_format((float)($account->confirmed_receipts ?? 0), 2) }}</p></article>@empty<div class="rounded-xl border bg-white p-10 text-center text-slate-500 sm:col-span-2">{{ __('payments.account_required') }}</div>@endforelse</div><form method="POST" action="{{ route('owner.payments.accounts.store') }}" class="rounded-xl border bg-white p-5">@csrf<h2 class="font-bold">{{ __('payments.new_account') }}</h2><div class="mt-4 grid gap-3"><select name="payment_method_id" required class="rounded-lg border-slate-200"><option value="">{{ __('payments.payment_method') }}</option>@foreach($methods as $method)<option value="{{ $method->id }}">{{ $method->name }}</option>@endforeach</select><input name="name" required class="rounded-lg border-slate-200" placeholder="{{ __('payments.account_name') }}"><input name="account_reference" class="rounded-lg border-slate-200" placeholder="{{ __('payments.account_reference') }}"><button class="rounded-lg bg-blue-700 px-4 py-3 font-bold text-white">{{ __('payments.create_account') }}</button></div></form></section>
        <section x-show="tab==='debts'" class="rounded-xl border bg-white p-4"><div class="flex items-center justify-between"><div><h2 class="font-bold">{{ __('payments.statements') }}</h2><p class="text-xs text-slate-500">{{ __('payments.statements_help') }}</p></div></div><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@forelse($customers as $customer)<a target="_blank" href="{{ route('owner.payments.customers.statement',$customer) }}" class="rounded-lg border p-3 hover:border-blue-300 hover:bg-blue-50"><p class="font-bold">{{ $customer->name }}</p><p class="text-xs text-slate-500">{{ __('payments.balance') }}: {{ $business->currency }} {{ number_format((float)($customer->ledger_debits ?? 0)-(float)($customer->ledger_credits ?? 0),2) }}</p></a>@empty<p class="text-sm text-slate-500">{{ __('payments.no_customers') }}</p>@endforelse</div></section>

        <section x-show="tab==='history'" x-cloak class="rounded-xl border border-rose-100 bg-white p-4"><h2 class="font-bold">{{ __('payments.correction') }}</h2><p class="text-xs text-slate-500">{{ __('payments.correction_help') }}</p><div class="mt-3 grid gap-2 lg:grid-cols-2">@foreach($payments->filter(fn($payment) => $payment->status === \App\Enums\PaymentRecordStatus::Confirmed) as $payment)<form method="POST" action="{{ route('owner.payments.reverse',$payment) }}" class="flex gap-2 rounded-lg border p-3">@csrf<div class="min-w-0 flex-1"><p class="font-bold">{{ $payment->payment_number }} · {{ $business->currency }} {{ number_format((float)$payment->amount,2) }}</p><input name="reason" required minlength="10" class="mt-2 w-full rounded-lg border-rose-200 text-sm" placeholder="{{ __('payments.reverse_reason') }}"></div><button class="self-end rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">{{ __('payments.reverse') }}</button></form>@endforeach</div></section>

        <section x-show="tab==='debts'" class="rounded-xl border bg-white p-4"><h2 class="font-bold">{{ __('payments.walk_in_sales') }}</h2><div class="mt-3 grid gap-3 lg:grid-cols-2">@forelse($walkInSales as $sale)<form method="POST" action="{{ route('owner.payments.sales.store',$sale) }}" class="rounded-lg border p-3">@csrf<div class="flex justify-between"><div><p class="font-bold">{{ $sale->sale_number }}</p><p class="text-xs text-slate-500">{{ $sale->walk_in_name ?? __('payments.walk_in_customer') }}</p></div><p class="font-bold text-amber-600">{{ $business->currency }} {{ number_format((float)$sale->outstanding_amount,2) }}</p></div><div class="mt-3 flex flex-wrap gap-2"><select name="payment_account_id" required class="min-w-36 flex-1 rounded-lg border-slate-200 text-sm"><option value="">{{ __('payments.payment_account') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input name="amount" type="number" min="0.01" max="{{ $sale->outstanding_amount }}" step="0.01" value="{{ $sale->outstanding_amount }}" class="w-32 rounded-lg border-slate-200 text-sm"><input name="external_reference" class="w-36 rounded-lg border-slate-200 text-sm" placeholder="{{ __('payments.reference') }}"><button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">{{ __('payments.pay_receipt') }}</button></div></form>@empty<p class="text-sm text-slate-500">{{ __('payments.no_walk_in') }}</p>@endforelse</div></section>

        <section x-show="tab==='debts'" class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach(__('payments.aging') as $key=>$label)<div class="rounded-xl border bg-white p-4"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-1 font-bold {{ $key==='days_61_plus'?'text-rose-600':'' }}">{{ $business->currency }} {{ number_format($aging[$key],2) }}</p></div>@endforeach</section>

        <section x-show="tab==='accounts'" x-cloak class="rounded-xl border bg-white p-5"><h2 class="font-bold">{{ __('payments.credit_policy') }}</h2><p class="mt-1 text-xs text-slate-500">{{ __('payments.credit_policy_help') }}</p><form method="POST" action="{{ route('owner.payments.credit-policy.update') }}" class="mt-3 flex flex-wrap gap-2">@csrf @method('PUT')<select name="credit_limit_policy" class="rounded-lg border-slate-200 text-sm"><option value="warn" @selected($creditPolicy==='warn')>{{ __('payments.warn_allow') }}</option><option value="require_approval" @selected($creditPolicy==='require_approval')>{{ __('payments.require_approval') }}</option><option value="block" @selected($creditPolicy==='block')>{{ __('payments.block_confirmation') }}</option></select><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">{{ __('payments.save_policy') }}</button></form></section>

        <section x-show="tab==='transfers'" x-cloak class="grid gap-5 lg:grid-cols-3">
            <form method="POST" action="{{ route('owner.payments.transfers.store') }}" class="rounded-xl border bg-white p-5">@csrf<h2 class="font-bold">{{ __('payments.transfer_accounts') }}</h2><div class="mt-4 grid gap-3"><select name="from_account_id" required class="rounded-lg border-slate-200"><option value="">{{ __('payments.from_account') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $business->currency }} {{ number_format((float)$account->current_balance,2) }}</option>@endforeach</select><select name="to_account_id" required class="rounded-lg border-slate-200"><option value="">{{ __('payments.to_account') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input name="amount" type="number" min="0.01" step="0.01" required class="rounded-lg border-slate-200" placeholder="{{ __('payments.amount') }}"><input name="reason" minlength="10" required class="rounded-lg border-slate-200" placeholder="{{ __('payments.business_reason') }}"><button class="rounded-lg bg-blue-700 px-4 py-3 font-bold text-white">{{ __('payments.request_transfer') }}</button></div></form>
            <div class="space-y-3 lg:col-span-2">@forelse($transfers as $transfer)<article class="rounded-xl border bg-white p-4"><div class="flex justify-between gap-2"><div><p class="font-bold">{{ $transfer->transfer_number }}</p><p class="text-xs text-slate-500">{{ $transfer->fromAccount->name }} → {{ $transfer->toAccount->name }} · {{ $business->currency }} {{ number_format((float)$transfer->amount,2) }}</p></div><span class="text-xs font-bold uppercase">{{ $transfer->status }}</span></div><p class="mt-2 text-sm">{{ $transfer->reason }}</p>@if($transfer->status==='pending' && $transfer->requested_by !== auth()->id())<form method="POST" action="{{ route('owner.payments.transfers.decision',$transfer) }}" class="mt-3 flex gap-2">@csrf @method('PUT')<input name="reason" required minlength="10" class="min-w-0 flex-1 rounded-lg border-slate-200 text-sm" placeholder="{{ __('payments.decision_evidence') }}"><button name="decision" value="approve" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">{{ __('payments.approve') }}</button><button name="decision" value="reject" class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">{{ __('payments.reject') }}</button></form>@endif</article>@empty<div class="rounded-xl border bg-white p-10 text-center text-slate-500">{{ __('payments.no_transfers') }}</div>@endforelse</div>
        </section>

        <section x-show="tab==='cash'" x-cloak class="grid gap-5 lg:grid-cols-3">
            <form method="POST" action="{{ route('owner.payments.cash-sessions.store') }}" class="rounded-xl border bg-white p-5">@csrf<h2 class="font-bold">{{ __('payments.open_cash_session') }}</h2><div class="mt-4 grid gap-3"><select name="payment_account_id" required class="rounded-lg border-slate-200"><option value="">{{ __('payments.cash_account') }}</option>@foreach($accounts->filter(fn($account) => $account->method->type === \App\Enums\AccountType::Cash) as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input name="opening_cash" type="number" min="0" step="0.01" required class="rounded-lg border-slate-200" placeholder="{{ __('payments.opening_cash') }}"><button class="rounded-lg bg-blue-700 px-4 py-3 font-bold text-white">{{ __('payments.open_session') }}</button></div></form>
            <div class="space-y-3 lg:col-span-2">@forelse($cashSessions as $session)<article class="rounded-xl border bg-white p-4"><div class="flex justify-between"><div><p class="font-bold">{{ $session->account->name }}</p><p class="text-xs text-slate-500">{{ __('payments.opened_by', ['date' => $session->opened_at->format('d M Y H:i'), 'name' => $session->opener->name]) }}</p></div><span class="text-xs font-bold uppercase {{ $session->status==='open'?'text-emerald-600':'text-slate-500' }}">{{ $session->status }}</span></div><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p class="text-slate-500">{{ __('payments.opening') }}</p><p class="font-bold">{{ $business->currency }} {{ number_format((float)$session->opening_cash,2) }}</p></div><div><p class="text-slate-500">{{ __('payments.expected') }}</p><p class="font-bold">{{ $session->expected_closing_cash === null ? __('payments.open') : $business->currency.' '.number_format((float)$session->expected_closing_cash,2) }}</p></div><div><p class="text-slate-500">{{ __('payments.difference') }}</p><p class="font-bold">{{ $session->difference_amount === null ? '—' : $business->currency.' '.number_format((float)$session->difference_amount,2) }}</p></div></div>@if($session->status==='open')<form method="POST" action="{{ route('owner.payments.cash-sessions.close',$session) }}" class="mt-3 flex flex-wrap gap-2">@csrf @method('PUT')<input name="actual_closing_cash" type="number" min="0" step="0.01" required class="w-40 rounded-lg border-slate-200 text-sm" placeholder="{{ __('payments.actual_cash') }}"><input name="difference_reason" class="min-w-52 flex-1 rounded-lg border-slate-200 text-sm" placeholder="{{ __('payments.cash_difference_reason') }}"><button class="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{{ __('payments.close_reconcile') }}</button></form>@endif</article>@empty<div class="rounded-xl border bg-white p-10 text-center text-slate-500">{{ __('payments.no_cash_sessions') }}</div>@endforelse</div>
        </section>
    </div>
    <script>function payments(){return{tab:@js(in_array(request('tab'), ['debts','history','accounts','transfers','cash'], true) ? request('tab') : 'debts')}}</script>
</x-app-layout>
